### ISSUE TITLE
Compile for Mips

### ISSUE THREAD

**Issue by speatzle** [corosync/corosync-qdevice#12]
Hey,
i am trying to get the qdevice compiled for MIPS.
Can i get some Instructions/Tips on how to do it?

**Comment by jfriesse** [comment]
@speatzle: Qdevice really doesn't use anything special, just standard autotools, so it should work same way as any other autotools based project (= ./autogen.sh, ./configure, make, make install). Debian has mips version in repositories https://packages.debian.org/sid/corosync-qdevice so it should work (at least compilation).
