### ISSUE TITLE
./configure fails on FreeBSD

### ISSUE THREAD

**Issue by Foxi352** [corosync/corosync-qdevice#25]
On FreeBSD freebsd 12.3-RELEASE-p6

`./configure`

```
[...]
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
./configure: 4715: Syntax error: word unexpected (expecting ")")
```

**Comment by fabbione** [comment]
@Foxi352 are you using gmake?

**Comment by fabbione** [comment]
https://ci.kronosnet.org/view/corosync/job/corosync-build-all-voting/corosync-build-all-voting=freebsd-12-x86-64/1727/consoleFull

**Comment by fabbione** [comment]
also, what version of corosync are you trying to build?

**Comment by fabbione** [comment]
Apology, I sent you the wrong link to the build log: https://ci.kronosnet.org/view/qdevice/job/qdevice-build-all-voting/qdevice-build-all-voting=freebsd-12-x86-64/304/console

**Comment by Foxi352** [comment]
Thanks for your quick reply @fabbione. I have a two node Proxmox 7 Cluster and want to install a qdevice on a FreeBSD 12.3 machine for quorum.

I redid from scratch and added the gmake package.
Here is the full story:

I did a fresh clean install ofFreeBSD 12.3 and cloned the `master` branch:
```
git clone https://github.com/corosync/corosync-qdevice.git
```
I then added the minimum packages:
```
pkg install git autoconf automake gmake gcc
```

Full output of what i did after git clone:
```
root@freebsd:~/git/corosync-qdevice # ./autogen.sh
Building configuration system...
Now run ./configure and make
root@freebsd:~/git/corosync-qdevice # ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
./configure: 4715: Syntax error: word unexpected (expecting ")")
root@freebsd:~/git/corosync-qdevice #
```

**Comment by fabbione** [comment]
I am using bash in my environments and you need to export MAKE=gmake. Or try the equivalent for the shell you are using.

**Comment by fabbione** [comment]
oh another detail, you want the main branch.. master is obsoleted.

**Comment by Foxi352** [comment]
Np, to make it easier for support i switched to bash
```
[root@freebsd ~]# echo $SHELL
/usr/local/bin/bash
```
I also exported MAKE now.
```
[root@freebsd ~]# echo $MAKE
gmake
```
I am indeed in `main` branch. Just wrote `master` because of .... well... old habits :-)
```
git branch
* main
```

I wiped the folder, did a new `git clone`, a new `./autogen.sh` and a new `./configure`.
Result is still the same:
```
[...]
checking dependency style of gcc... gcc3
./configure: 4715: Syntax error: word unexpected (expecting ")")
```

Maybe some other dependency missing ? Some other package to install ?
Although the message should then state what is missing ... So it's probably another problem ...

**Comment by fabbione** [comment]
From out logs:

16:23:20 checking whether gmake sets $(MAKE)... yes
16:23:20 checking whether gmake supports the include directive... yes (GNU style)
16:23:20 checking whether gmake supports nested variables... yes
16:23:20 checking dependency style of gcc... gcc3
16:23:20 checking build system type... amd64-unknown-freebsd12.3
16:23:20 checking host system type... amd64-unknown-freebsd12.3
16:23:20 checking how to print strings... printf

Nothing specific to qdevice is checked there. I just tried to reproduce your issue manually:

[root@freebsd-12-x86-64 ~]# git clone https://github.com/corosync/corosync-qdevice.git
[snip]
[root@freebsd-12-x86-64 ~/corosync-qdevice]# export MAKE=gmake
[root@freebsd-12-x86-64 ~/corosync-qdevice]# ./autogen.sh
Building configuration system...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:11: installing './compile'
configure.ac:16: installing './config.guess'
configure.ac:16: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
qdevices/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
Now run ./configure and make
[root@freebsd-12-x86-64 ~/corosync-qdevice]# ./configure --disable-systemd
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether gmake sets $(MAKE)... yes
checking whether gmake supports the include directive... yes (GNU style)
checking whether gmake supports nested variables... yes
checking dependency style of gcc... gcc3
checking build system type... amd64-unknown-freebsd12.3
checking host system type... amd64-unknown-freebsd12.3
checking how to print strings... printf
[snip]

notice the difference at ./autogen.sh time, probably you are missing libtool

[root@freebsd-12-x86-64 ~/corosync-qdevice]# pkg info |grep libto
libtool-2.4.7                  Generic shared library support script

**Comment by Foxi352** [comment]
Indeed `libtool` was missing. I installed it now.
```
[1/1] Fetching libtool-2.4.7.pkg: 100%  361 KiB 369.8kB/s    00:01
```
`./autogen.sh` produces more lines now.
```
Building configuration system...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Now run ./configure and make
```

But still it is missing the `configure.ac` lines you had, i mean the following:
```
configure.ac:11: installing './compile'
configure.ac:16: installing './config.guess'
configure.ac:16: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
qdevices/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
```

Is there maybe another dependency missing ?

Anyways, it's going a bit further now, but the `./configure: PKG_PROG_PKG_CONFIG: not found` strikes my eyes.
I tried `pkg install pkg-config` but it did not find that package.
```
[root@freebsd ~/git/corosync-qdevice]# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether gmake sets $(MAKE)... yes
checking whether gmake supports the include directive... yes (GNU style)
checking whether gmake supports nested variables... yes
checking dependency style of gcc... gcc3
checking build system type... amd64-unknown-freebsd12.3
checking host system type... amd64-unknown-freebsd12.3
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/local/bin/ld
checking if the linker (/usr/local/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/local/bin/nm -B
checking the name lister (/usr/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 393216
checking how to convert amd64-unknown-freebsd12.3 file names to amd64-unknown-freebsd12.3 format... func_convert_file_noop
checking how to convert amd64-unknown-freebsd12.3 file names to toolchain format... func_convert_file_noop
checking for /usr/local/bin/ld option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/local/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/local/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... freebsd12.3 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether gmake supports nested variables... (cached) yes
configure: building in place srcdir:.
checking for gawk... (cached) nawk
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking how to run the C preprocessor... gcc -E
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking whether ln -s works... yes
checking whether gmake sets $(MAKE)... (cached) yes
./configure: PKG_PROG_PKG_CONFIG: not found
checking for bash... /usr/local/bin/bash
checking for groff... no
checking for uid_t in sys/types.h... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for size_t... yes
checking for ssize_t... yes
./configure: 14506: Syntax error: word unexpected (expecting ")")
```

**Comment by fabbione** [comment]
https://github.com/kronosnet/ci-tools/blob/main/ci-update-freebsd

those are the full dependencies I install on BSD nodes, but that would be everything and more than you need.

the package is called pkgconf

**Comment by Foxi352** [comment]
Thanks. That link will help me. I added `pkgconf` and `nss`. I also have exactly the same lines now for autogen as you had.
But where can i get `libcorosync_common from ? Did not find that in your dependencies, and package is not in repo.
I am sorry for the issue, because at the end this was now more a support thread than an issue.

**Comment by fabbione** [comment]
No worries at all, you want to build corosync.git in the same version as proxmox and install it.

**Comment by fabbione** [comment]
that in turns, require also kronosnet (the version in BSD might be old)

**Comment by fabbione** [comment]
[root@freebsd-12-x86-64 ~/corosync-qdevice]# pkg search corosync
corosync2-2.4.5_1              Corosync Cluster Engine
corosync3-2.99.5_1             Corosync Cluster Engine

**Comment by fabbione** [comment]
that might be easier as well.

**Comment by Foxi352** [comment]
Installing `corosync3-2.99.5_1` did the trick :-) (Have 3.1.5 running in Proxmox)
`./configure` is now working and `make` also seems to run ...

Although it's hanging on `sed` forever. But i will leave it running for now because maybe that's normal ? 
```
[...]
  CCLD     corosync-qdevice
  CC       corosync-qdevice-tool.o
  CCLD     corosync-qdevice-tool
sed -e 's#@''DATADIR@#/usr/share#g'  -e 's#@''BASHPATH@#/usr/local/bin/bash#g'  -e 's#@''COROSYSCONFDIR@#/etc/corosync#g'   > corosync-qnetd-certutil
```

**Comment by fabbione** [comment]
It shouldn´t take more than a few milliseconds to do that.

**Comment by Foxi352** [comment]
OK, then i have my next problem :-)
Difficult to debug as there is no error .... A ctrl-c just shows
```
^Cmake[3]: *** corosync-qnetd-certutil removed
*** Signal 2
*** Signal 2
*** Signal 2
*** Signal 2
```

So nothing special

**Comment by fabbione** [comment]
oh I know why...

export MAKE=gmake
./autogen.sh
./configure --disable-systemd
gmake clean
gmake all

if you did call make, it´s still BSD-make. I think I have done that mistake 2.4G times....

**Comment by Foxi352** [comment]
Oh boy.... you were right of course ;-)
I will now try to move the compiled binary to another host without build system installed. But that is beyond the scope of this issue. So i will close this issue for now.

I sincerely thank you for your time and reactivity. If ever someone stumbles over this issue and tries to compile on a fresh FreeBSD install, here is the complete list of packages to install:

```
pkg install git autoconf automake gmake gcc pkgconf libtool nss corosync3-2.99.5_1
```
